#### Dataset from: https://www.kaggle.com/competitions/titanic

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

## Basic Statistics

In [21]:
df = pd.read_csv("./titanic.csv")
num_cols = df.select_dtypes(include=np.number).columns.tolist()
cat_cols = df.select_dtypes(include='object').columns.tolist()

/tmp/ipykernel_87424/41176752.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns.tolist()

In [7]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [22]:
# VARIANCE
df[num_cols].var()

PassengerId    66231.000000
Survived           0.236772
Pclass             0.699015
Age              211.019125
SibSp              1.216043
Parch              0.649728
Fare            2469.436846
dtype: float64

In [16]:
# STANDARD DEVIATION
df[num_cols].std()

PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64

In [17]:
# QUARTILE (Q1, Q2, Q3)
df[num_cols].quantile([0.25, 0.50, 0.75])

      PassengerId  Survived  Pclass     Age  SibSp  Parch     Fare
0.25        223.5       0.0     2.0  20.125    0.0    0.0   7.9104
0.50        446.0       0.0     3.0  28.000    0.0    0.0  14.4542
0.75        668.5       1.0     3.0  38.000    1.0    0.0  31.0000

In [18]:
# PERCENTILE
df[num_cols].quantile([0.10, 0.25, 0.50, 0.75, 0.90, 0.95])

      PassengerId  Survived  Pclass     Age  SibSp  Parch       Fare
0.10         90.0       0.0     1.0  14.000    0.0    0.0    7.55000
0.25        223.5       0.0     2.0  20.125    0.0    0.0    7.91040
0.50        446.0       0.0     3.0  28.000    0.0    0.0   14.45420
0.75        668.5       1.0     3.0  38.000    1.0    0.0   31.00000
0.90        802.0       1.0     3.0  50.000    1.0    2.0   77.95830
0.95        846.5       1.0     3.0  56.000    3.0    2.0  112.07915

In [19]:
# SKEWNESS
df[num_cols].skew()

PassengerId    0.000000
Survived       0.478523
Pclass        -0.630548
Age            0.389108
SibSp          3.695352
Parch          2.749117
Fare           4.787317
dtype: float64

In [20]:
# KURTOSIS
df[num_cols].kurt()

PassengerId    -1.200000
Survived       -1.775005
Pclass         -1.280015
Age             0.178274
SibSp          17.880420
Parch           9.778125
Fare           33.398141
dtype: float64

## Distribusi Data

In [23]:
# HISTOGRAM
df[num_cols].hist(figsize=(12, 8), bins=20, edgecolor='black')
plt.suptitle('Histogram', fontsize=14)
plt.tight_layout()
plt.show()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.